import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://dtuat.euf20.gravty.io/#/login');
  await page.getByRole('textbox', { name: 'Username*' }).click();
  await page.getByRole('textbox', { name: 'Username*' }).fill('shubham.gupta1@telekom-digital.com');
  await page.getByRole('textbox', { name: 'Password*' }).fill('New@123456789');
  await page.getByRole('button', { name: 'Log In' }).click();
  await page.getByRole('button', { name: 'No' }).click();
  await page.getByRole('button', { name: 'Setup Later' }).click();
  await page.goto('https://dtuat.euf20.gravty.io/#/offer/home');
  await page.locator("//img[@title='Clear']").click();
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.waitForTimeout(2000);
  await page.locator("//div[@class='offer-home__header__data__button__tooltip__dropdown']//img[@src='assets/img/reward_icon.png']").click();
  //await page.locator('span').filter({ hasText: 'Reward' }).click();
  await page.waitForTimeout(5000);
  await page.locator('#noscrol_21').click();
  await page.locator('#noscrol_21').fill('TestGreeceDemo2');
  await page.getByRole('textbox', { name: 'Start typing Sponsor\'s name' }).click();
  await page.getByRole('textbox', { name: 'Start typing Sponsor\'s name' }).fill('1');
  await page.getByRole('textbox', { name: 'Start typing Sponsor\'s name' }).click();
  await page.getByRole('textbox', { name: '1' }).dblclick();
  await page.getByRole('textbox', { name: '1' }).fill('DT Greece');
  await page.getByText('DT Greece', { exact: true }).click();
  await page.locator('gravty-date-input-field').getByRole('button', { name: 'icon' }).click();
  await page.getByRole('table').filter({ hasText: 'February January February' }).getByLabel('20').click();
  await page.getByRole('button', { name: '30' }).click();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('gravty-splitted-text-select-field').filter({ hasText: 'Maximum Usage Limit Select' }).getByPlaceholder('Unlimited If Empty').click();
  await page.locator('gravty-splitted-text-select-field').filter({ hasText: 'Maximum Usage Limit Select' }).getByPlaceholder('Unlimited If Empty').fill('1000');
  await page.getByRole('button', { name: 'Per Day' }).click();
  await page.getByRole('textbox', { name: 'Unlimited If Empty' }).click();
  await page.getByRole('textbox', { name: 'Unlimited If Empty' }).fill('10');
  await page.getByRole('button', { name: 'Per Day' }).click();
  await page.locator('app-offer-custom-attributes-form').getByRole('img', { name: 'expand Img' }).click();
  await page.getByRole('button', { name: 'Select Attribute' }).click();
  await page.getByRole('button', { name: 'Select', exact: true }).click();
  await page.getByRole('option', { name: 'DT Greece' }).getByRole('listitem').click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Select Attribute' }).click();
  await page.getByRole('textbox', { name: 'Enter Value' }).click();
  await page.getByRole('textbox', { name: 'Enter Value' }).fill('10');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByText('Skip to main content powered').press('Tab');
  await page.getByRole('button', { name: 'Select Attribute' }).click();
  await page.getByRole('textbox', { name: 'Enter Value' }).click();
  await page.getByRole('textbox', { name: 'Enter Value' }).fill('100');
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Select Attribute' }).click();
  await page.getByRole('button', { name: 'Select', exact: true }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Select Attribute' }).click();
  await page.getByRole('button', { name: 'Select', exact: true }).click();
  await page.locator('div:nth-child(7) > .custom-attributes__content__record__right-record').click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Select Attribute' }).click();
  await page.getByRole('button', { name: 'Select', exact: true }).click();
  await page.getByRole('button', { name: 'Telekom Offer Type', exact: true }).click();
  await page.getByRole('button', { name: 'Select', exact: true }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Select Attribute' }).click();
  await page.getByRole('button', { name: 'Select', exact: true }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Select Attribute' }).click();
  await page.getByRole('button', { name: 'Select', exact: true }).click();
  await page.getByRole('button', { name: 'Add' }).click();
  await page.getByRole('button', { name: 'Select Attribute' }).click();
  await page.locator('#noscrol_18').click();
  await page.locator('#noscrol_18').fill('6912');
  await page.getByRole('button', { name: 'Select Locations' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Select KPIs' }).click();
  await page.getByRole('button', { name: 'Select Offer Rules' }).click();
  await page.locator('#blockly').click();
  await page.getByRole('status', { name: 'download icon' }).click();
  await page.locator('#importFile').click();
  await page.locator('#importFile').setInputFiles('offer_15631745_rules 3 (1).xml');
  await page.getByText('New Greece product ▾').click();
  await page.getByText('Test New').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('.blocklyMainBackground').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('.blocklyMainBackground').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.getByRole('button', { name: 'Multilingual Support' }).click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyEditableText > rect').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.getByText('1').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.getByRole('button', { name: 'Multilingual Support' }).click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.locator('.blocklyMainBackground').click();
  await page.locator('g:nth-child(2) > .blocklyPath').click();
  await page.getByRole('button', { name: 'Multilingual Support' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Finish' }).click();
  await page.getByText('TestGreeceDemo2').click();
  await page.getByText('In Planning', { exact: true }).click();
  await page.getByText('Launch', { exact: true }).click();
  await page.getByRole('button', { name: 'Change Status' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
});